### ISSUE TITLE
Compiled binary segfaults when run

### ISSUE THREAD

**Issue by jfilby** [openpeeps/denim#5]
Here's my test Nim program:

```nim
import myprogramapppkg/submodule

when defined napibuild:
  # Running `denim build myprogram.nim` compiles with `-d:napibuild`
  import denim # NAPI bindings
  import jsony

  init proc(module: Module) =
    module.registerFn(0, "getWelcomeMessage"):
      return %* getWelcomeMessage()

elif isMainModule:
  echo(getWelcomeMessage())
```

When I run the binary created in the bin directory I get a segfault 11. I suspect node-gyp has a problem somewhere. When I searched on this problem I saw that people logged similar issues for previous versions of node-gyp, but those are fixed by now.

Version information:

```sh
$ node --version
v18.16.0
$ node-gyp --version
v9.4.0
$ nim --version
Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release
```

**Comment by georgelemon** [comment]
All good here. This is weird. Try with `bun`?

Btw, `jsony` is not necessary here.

```
$ node -v
v18.16.1

$ node-gyp --version
v9.4.0

Nim Compiler Version 1.6.12 [Linux: amd64]
Compiled at 2023-03-10
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 1aa9273640c0c51486cf3a7b67282fe58f360e91
active boot switches: -d:release
```

**Comment by jfilby** [comment]
I upgraded to Node 18.16.1, but it didn't help. I'm running Fedora, but that shouldn't be a problem.

How would I test with Bun? Does it have its own extension compiler?

**Comment by georgelemon** [comment]
No, but you can try run the compiled `.node` addon with Bun.

**Comment by jfilby** [comment]
Here's a similar issue someone has with a Go add-on segfaulting: https://github.com/nodejs/node-gyp/issues/2695. Although their case segfaults at the end, while mine segfaults at the very beginning. That's why I think this is a node-gyp issue.

**Comment by jfilby** [comment]
I might try Bun, but I'm not optimistic.

My gcc version: (GCC) 13.1.1 20230614 (Red Hat 13.1.1-4).
