### ISSUE TITLE
Frequent: SIGSEGV: Illegal storage access. (Attempt to read from nil?)

### ISSUE THREAD

**Issue by jfilby** [openpeeps/denim#8]
My node module is causing Node to die quite often. It is typically (always?) a Nim GC function:

```
$HOME/.choosenim/toolchains/nim-1.6.14/lib/system/gc.nim(486) newObj
$HOME/.choosenim/toolchains/nim-1.6.14/lib/system/gc_common.nim(422) prepareDealloc
```

I'm not sure if a different GC would help, I think Denim uses the default? I usually specify the ORC GC when compiling the code I'm using for the node addon. I think it might help if Denim had an option to pass in extra args to the Nim compiler called by the Denim build command.

**Comment by georgelemon** [comment]
Actually, you can create a `.nims` file!

`useMalloc` is added by default in [build command](https://github.com/openpeeps/denim/blob/main/src/denimpkg/commands/buildCommand.nim#L67). Maybe I should remove that so you can have full control

**Comment by jfilby** [comment]
I'm a bit late to use .nims files, but this worked perfectly. I set the GC to ORC. So far no sign of the error, and I've tested quite thoroughly. I think useMalloc should indeed be optional (not added by default).
